### ISSUE TITLE
Trace timings

### ISSUE THREAD

**Issue by ryanolson** [bloomen/transwarp#12]
Thank you for the wonderful library.

What do you think about adding some type of tracing/metrics interface?  It would be neat for a given execution of the graph to augment the dot-style graph with timing info.

**Comment by bloomen** [comment]
I think that’s a good idea. Do you have an idea for an interface yet? We obviously need to ensure that performance is unaffected for those users that don’t require timing information.

**Comment by ryanolson** [comment]
Not yet.  I just exploring your code.  The other thought is a combination of a registration and serialization mechanism, so given a library of functors, you could read in a graph and then execute it.

**Comment by bloomen** [comment]
I realized that timing tasks can be implemented quite easily using the existing listener interface. One just needs to write a listener that listens to the `after_started` and `before_finished` events. The timer would then be started when the former event is raised and stopped when the latter happens. The rest is then just adding a new field to the `node` class that carries a runtime of some sort to be output to the dot format.

**Comment by bloomen** [comment]
Implement with https://github.com/bloomen/transwarp/commit/76450e181dbbcd1b4de2d90f74d91259dd2b5008
