### ISSUE TITLE
Merge `node` into `itask`

### ISSUE THREAD

**Issue by bloomen** [bloomen/transwarp#20]
The goal is to remove confusion between task and node. There's no significant argument anymore to keep `node` around so the goal is to merge its fields (minus executor) into `itask` and add corresponding `accessor` methods. `itask` may have to be renamed pending discussions.

**Comment by bloomen** [comment]
Hey Ben, have you looked into this yet?

**Comment by ebatz** [comment]
Sorry, I've been completely swamped with other things.
I'm still very much interested in getting the object lifetime control working in transwarp, but can't tell when I'll get around to working towards it.

**Comment by bloomen** [comment]
No problem. I will take a look at the current issue. The lifetime control can then be implemented any time later.
