### ISSUE TITLE
std::result_of removed in C++20

### ISSUE THREAD

**Issue by aheysse** [bloomen/transwarp#28]
transwarp.h uses 
`using type = typename std::result_of<decltype(&std::shared_future<T>::get)(std::shared_future<T>)>::type;`

This doesn't compile on Visual Studio 2019 (v142) with <LanguageStandard>stdcpplatest</LanguageStandard> as C++20 removes this functionality.

The compiler has a number of macros to determine which STL/C++ standard it supports. You should be able to do this with an #ifdef albeit I don't know the macros/versions off the top of my head.

**Comment by bloomen** [comment]
Good catch! How do you like this change: https://github.com/bloomen/transwarp/commit/086f7f5b7a50a4734bf6a7c0bb033bd6a8bb909f
