### ISSUE TITLE
Transwarp doesn't seem to be fully move aware

### ISSUE THREAD

**Issue by aheysse** [bloomen/transwarp#29]
This could be more of a question than a bug, but is it intended to be able to package move only objects inside tasks? I've been looking at the code, and there seems to be some intent that transwarp is move aware, but it doesn't seem to be complete.

Minimum repo on VS2019 (v142) or Clang on godbolt: 
`    transwarp::make_task(transwarp::root, []() {
        return std::make_unique<int>();
    });`

What happens is that because transwarp::task has both overloads for set_value:
`    virtual void set_value(const typename transwarp::decay<result_type>::type& value) = 0;`
`    virtual void set_value(typename transwarp::decay<result_type>::type&& value) = 0;`

...both functions get instantiated in task_impl_proxy. With movable only ResultTypes, the first function will still get instantiated, but it will be invalid C++ as the function's implementation will eventually attempt to make a copy.

Is it intended that this does not work?

Cheers

**Comment by bloomen** [comment]
Thanks for the question!

The values held by tasks have to be copyable so your `value_type` cannot be a `unique_ptr`. 

The two `set_value` overloads simply provide the standard setter idiom for lvalue and rvalue references.

**Comment by aheysse** [comment]
Thanks for answering. In theory it could be made to work with movable only types - would that be something you'd be interested in?

**Comment by bloomen** [comment]
I don't think that the current architecture and requirements can work with move-only types. One requirement of a transwarp graph is that it can be scheduled any number of times. Another is that task outputs can be shared by multiple children. It's not clear to me how you would satisfy these requirements with move-only types.
