### ISSUE TITLE
Tasks are not executed

### ISSUE THREAD

**Issue by tim-lebedkov** [bloomen/transwarp#33]
My code does not seem to execute at all. 

```cpp
        auto t = transwarp::make_task(transwarp::root,
            [this, id, url] {
                qCWarning(npackdImportant) << "downloadFileRunnable";
                return this->downloadFileRunnable(id, url);
            });
        t->add_listener(transwarp::event_type::after_finished,
                downloadFileListener);

        t->schedule(threadPool);

```

**Comment by bloomen** [comment]
Can you provide a fully functional cpp file so we can determine what the problem is?
What you posted should work but it depends on what `threadPool` does and when you're expecting the task to be executed.

**Comment by tim-lebedkov** [comment]
Before I write a complete example this is the definition of threadPool:

```cpp
transwarp::parallel FileLoader::threadPool{10};
```

I expect the task to start immediately after "schedule" as in std::async. Isn't it the case?

**Comment by bloomen** [comment]
No. `schedule` only schedules the task for asynchronous execution in the thread pool. If you want to see it run immediately after you need to also call `wait` or `get`.

**Comment by tim-lebedkov** [comment]
I changed my implementation to use `transwarp::detail::thread_pool` and not everything works. I like how easy it was to initialize a thread.

```c++
FileLoader::threadPool{10, [](size_t){
    SetThreadPriority(GetCurrentThread(), THREAD_PRIORITY_LOWEST);
    SetThreadPriority(GetCurrentThread(), THREAD_MODE_BACKGROUND_BEGIN);
}};
```

Could you please move the thread_pool to the public API?

**Comment by bloomen** [comment]
The thread pool class can remain an implementation detail since you can get the same functionality through the `tw::parallel` executor.
