### ISSUE TITLE
readability and interface

### ISSUE THREAD

**Issue by CharlesJQuarra** [bloomen/transwarp#35]
Hi,

this library is really neat and tidy in general. Which is why it seems a shame that some of the readability of the interfaces are somewhat clunky

consider this example:

```
auto task = pool.wait_for_next_task(); // Get the next available task
auto input = task->tasks()[0];
static_cast<tw::task<std::shared_ptr<std::vector<double>>>*>(input)->set_value(data);
```
https://github.com/bloomen/transwarp/blob/master/examples/wide_graph_with_pool.cpp#L75-L77

from the name of the `wait_for_next_task` one would expect that this is returning indeed available/idle tasks in breadth order. However the 2nd line suggests you are getting an array of said tasks. Couldn't this be written in a more concise interface on a single line?

I understand that the cast on the 3rd line is probably due to not knowing if you are expecting a value or consumer task, but perhaps (since the intent here is to feed root/value tasks) something like `wait_for_next_root/value_task` would be a better interface, which could avoid this static_cast smudge on the example code

**Comment by bloomen** [comment]
Hi, thanks for your feedback and sorry for the late reply.
I am definitely open to improvements here. Note that the `task_pool` is supposed to be used with the final task of a graph so when `wait_for_next_task` is called it returns a cloned object of the final task. When you then call `task->tasks()` you'll get all tasks in the graph returned by-breadth. The container returned is just a vector of `itask` so there's no way to know at this point which element is which task impl. So I think a cast cannot be prevented. However, it could be wrapped in a helper function?
Maybe like this: `task->parent_at<std::vector<double>>(0)` ?
