### ISSUE TITLE
next() method documented but does not exist

### ISSUE THREAD

**Issue by Alex-PLACET** [bloomen/transwarp#37]
Hello,

I saw this part in the documentation:

> Generally, tasks are created using make_task which allows for any number of parents. However, it is a common use case for a child to only have one parent. For this, next() can be directly called on the parent object to create a continuation:
> auto child = tw::make_task(tw::root, []{ return 42; })->next(tw::consume, functor);

I don't see anything related to this method in the code. Is it something planned or removed ?

Great work btw

**Comment by Alex-PLACET** [comment]
I finally saw that it's `then` and not `next`

**Comment by bloomen** [comment]
Yes indeed. This is a bug in the documentation. Thanks for reporting!
