### ISSUE TITLE
Comparison with cpp-taskflow

### ISSUE THREAD

**Issue by DJuego** [bloomen/transwarp#7]
Thank you for your very hard work! 

I keep an eye on in this library and [cpp-taskflow](https://github.com/twhuang-uiuc/cpp-taskflow). Both libraries are very alive and they seems powerful. I think a comparison between the two would be interesting. 

I must admit that I have not done anything serious yet but I feel very fortunate and grateful for these projects. Variety in alternatives, aproaches, options makes us all stronger,  Thanks again!

DJuego

**Comment by bloomen** [comment]
I had a look at cpp-taskflow. From what I can tell so far the main differences are that cpp-taskflow
- requires C++17 whereas transwarp uses C++11
- does not support custom executors
- can result in cyclic graphs (impossible with transwarp)
- has no visual studio support
- supports `parallel_for` (could be a future feature for transwarp)

**Comment by bloomen** [comment]
Thanks for your feedback! I will incorporate your comments in future versions. Cheers!
